/* Page détail issue du même système visuel : fiche projet éditoriale, terminal sombre et navigation claire. */
import { type MouseEvent } from "react";
import { ArrowLeft, ArrowUpRight, CheckCircle2, Github, ShieldCheck } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";

const details: Record<string, { title: string; type: string; status: string; intro: string; description: string; stack: string[]; bullets: string[]; site?: string; github?: string; signature?: string; audiences?: string; features?: string[]; architecture?: Array<[string, string]>; security?: string; role?: string }> = {
  "koumanplay": { title: "KoumanPlay", type: "Jeu culturel intergénérationnel", status: "Lauréat", intro: "Un prototype numérique pensé pour transmettre le patrimoine culturel ivoirien de manière vivante.", description: "KoumanPlay transforme les proverbes, les contes audio et les défis interactifs en une expérience accessible à plusieurs groupes ethniques. Le projet a été présenté au Hack & Train Pont numérique 2026.", stack: ["HTML5", "CSS3", "JavaScript"], bullets: ["Structuration d’une expérience ludique et accessible", "Mise en scène de contenus culturels audio", "Prototype réalisé dans un contexte de hackathon"], signature: "Faire vivre la culture par le jeu.", audiences: "Familles, jeunes publics et personnes souhaitant redécouvrir le patrimoine ivoirien.", features: ["Proverbes et contes audio organisés par univers", "Défis interactifs pour apprendre en jouant", "Parcours pensé pour favoriser la transmission intergénérationnelle"], architecture: [["Interface", "HTML5, CSS3 et JavaScript ES6+"], ["Expérience", "Navigation ludique et contenus multimédias"], ["Responsive", "Adaptation mobile et desktop"], ["Conception", "Prototype rapide orienté usage"]], role: "Conception de l’expérience, développement de l’interface, structuration des contenus et réalisation du prototype présenté au hackathon." },
  "tontinci": { title: "TontinCi", type: "Application mobile", status: "En cours", intro: "Une application mobile pour simplifier la gestion quotidienne des tontines.", description: "TontinCi permet de créer ou rejoindre des groupes, de suivre les cotisations et de consulter l’historique des transactions dans une interface claire.", stack: ["Flutter", "Dart", "Supabase", "Iconsax"], bullets: ["Gestion des groupes et des membres", "Suivi des cotisations et de l’historique", "Interface mobile pensée pour un usage régulier"], signature: "Rendre la tontine plus simple à piloter.", audiences: "Membres de tontines, responsables de groupes et utilisateurs mobiles.", features: ["Création et adhésion à des groupes", "Suivi des cotisations et des échéances", "Historique des transactions et vue synthétique du groupe"], architecture: [["Mobile", "Flutter et Dart"], ["Données", "Supabase"], ["Interface", "Iconsax et composants mobiles"], ["Conception", "Parcours orientés actions fréquentes"]], role: "Conception des parcours, développement de l’application mobile, intégration des données et structuration de l’expérience de gestion.", github: "https://github.com/YvanOssey/tontinci" },
  "choptaresi-ci": { title: "ChopTaResi CI", type: "Plateforme SaaS immobilière", status: "En cours", intro: "Une plateforme unique pour fluidifier la gestion immobilière entre propriétaires et locataires.", description: "ChopTaResi CI centralise les biens, les résidences, les locataires et les paiements, avec une authentification JWT pour sécuriser les accès.", stack: ["Node.js", "React", "MySQL", "JWT"], bullets: ["Gestion des biens et des résidences", "Authentification sécurisée par JWT", "Base de données relationnelle MySQL"], signature: "Centraliser la gestion immobilière sans friction.", audiences: "Propriétaires, gestionnaires de résidences, locataires et équipes immobilières.", features: ["Gestion des biens, résidences et locataires", "Suivi des paiements et des données immobilières", "Accès protégé par authentification JWT"], architecture: [["Frontend", "React"], ["Backend", "Node.js"], ["Données", "MySQL"], ["Sécurité", "JWT et contrôle des accès"]], role: "Analyse du besoin, conception de l’architecture, développement full-stack, modélisation des données et sécurisation des accès.", github: "https://github.com/YvanOssey/resimanage-ci" },
  "eduscan": { title: "EduScan", type: "Application mobile académique", status: "Académique", intro: "Une application de gestion de scolarité centrée sur la vérification rapide des paiements.", description: "EduScan utilise le scan de QR code pour vérifier les paiements étudiants et Supabase pour gérer les données de scolarité.", stack: ["Figma", "Flutter", "Dart", "Supabase"], bullets: ["Parcours étudiant prototypé dans Figma", "Vérification par QR code", "Synchronisation des données avec Supabase"], signature: "Vérifier plus vite, gérer plus sereinement.", audiences: "Étudiants, établissements et équipes chargées du suivi de scolarité.", features: ["Scan de QR code pour vérifier un paiement", "Parcours étudiant prototypé avant développement", "Gestion des données de scolarité avec Supabase"], architecture: [["Prototype", "Figma"], ["Mobile", "Flutter et Dart"], ["Données", "Supabase"], ["Usage", "Parcours court et vérification rapide"]], role: "Conception du parcours, prototypage de l’interface, développement mobile et intégration de la gestion des données." },
  "obvx": { title: "OBVX", type: "Boutique e-commerce", status: "Réalisé", intro: "Une expérience e-commerce responsive avec catalogue dynamique et panier interactif.", description: "OBVX présente des produits de façon structurée et propose une expérience d’achat adaptée aux différents formats d’écran.", stack: ["HTML5", "CSS3", "JavaScript"], bullets: ["Catalogue dynamique", "Panier interactif", "Interface responsive"], signature: "Faire passer le produit avant le bruit.", audiences: "Visiteurs mobiles et desktop à la recherche d’une expérience d’achat claire.", features: ["Catalogue produit structuré", "Panier interactif", "Présentation responsive et lisible"], architecture: [["Interface", "HTML5 et CSS3"], ["Interactions", "JavaScript ES6+"], ["Responsive", "Adaptation multi-écrans"], ["Expérience", "Navigation orientée conversion"]], role: "Conception de l’interface, développement des interactions, structuration du catalogue et optimisation responsive.", github: "https://github.com/YvanOssey/obvx" },
  "obc-aec": { title: "OBC & AEC", type: "Sites institutionnels sportifs", status: "Réalisé", intro: "Des prototypes web responsives pour valoriser les activités et les équipes de clubs sportifs.", description: "Ces maquettes institutionnelles présentent les actualités, les activités, les équipes et les événements des clubs avec un parcours de contact simple.", stack: ["HTML5", "CSS3", "JavaScript", "Formspree"], bullets: ["Présentation des activités et équipes", "Maquettes adaptées au mobile", "Formulaire de contact intégré"], signature: "Donner une présence digitale au collectif.", audiences: "Clubs sportifs, licenciés, supporters et partenaires.", features: ["Présentation des équipes et des activités", "Mise en avant des événements et actualités", "Formulaire de contact pour les échanges avec le club"], architecture: [["Interface", "HTML5 et CSS3"], ["Interactions", "JavaScript ES6+"], ["Contact", "Formspree"], ["Responsive", "Consultation mobile et desktop"]], role: "Conception des maquettes, développement des pages institutionnelles, intégration du formulaire et adaptation responsive.", github: "https://github.com/YvanOssey/Athl-tic-Elite-Club" },
  "story-s": { title: "Story’s", type: "Gestion de blanchisserie à domicile", status: "En développement", intro: "Une plateforme métier pour coordonner les collectes, les commandes et les tournées d’une blanchisserie à domicile.", description: "Story’s accompagne les particuliers dans la commande, le suivi et la livraison de leur linge, tout en donnant à l’équipe un espace privé pour piloter l’activité opérationnelle. Le paiement en ligne est prévu pour une phase ultérieure ; le fonctionnement actuel repose sur le paiement à la livraison.", stack: ["React 19", "TypeScript", "Node.js", "Express", "tRPC", "MySQL / TiDB", "Drizzle ORM"], bullets: ["Inscription et connexion des clients", "Suivi détaillé des commandes selon six statuts", "Gestion des créneaux, livreurs et tournées", "Notifications personnelles et opérationnelles"], signature: "Du linge collecté à la livraison, chaque étape compte.", audiences: "Particuliers utilisant un service de lavage, repassage, collecte et livraison, ainsi que les administrateurs, responsables d’atelier et livreurs de Story’s.", features: ["Parcours client avec commande réservée aux utilisateurs authentifiés", "Suivi de commande et affichage des créneaux confirmés", "Tableau de bord admin pour clients, commandes et paiements à encaisser", "Organisation du planning, des livreurs, des tournées et des affectations", "Cloche de notifications avec compteur, toast, lecture individuelle ou globale et suppression"], architecture: [["Frontend", "React 19, TypeScript, Vite et Tailwind CSS 4"], ["Composants", "UI inspirée de shadcn/ui et Lucide Icons"], ["API", "tRPC 11 et procédures client/admin"], ["Backend", "Node.js, Express 4 et TypeScript"], ["Données", "MySQL/TiDB, Drizzle ORM et migrations SQL"], ["Tests", "Vitest, TypeScript, Vite et esbuild"]], security: "Sessions par cookies sécurisés, comptes clients dédiés, comptes administrateurs protégés par email/mot de passe avec whitelist et vérification des autorisations côté serveur.", role: "Conception du produit et de l’architecture, développement des parcours client et admin, modélisation des données, gestion des rôles, tests et préparation d’un déploiement indépendant avec Docker, Nginx, HTTPS et sauvegardes.", github: "https://github.com/YvanOssey/storys-blanchisserie" },
  "clairdroit": { title: "ClairDroit", type: "Blog juridique full-stack", status: "En ligne", intro: "Un espace éditorial juridique administrable, sécurisé et déployé pour publier au rythme du contenu.", description: "ClairDroit combine un espace d’administration sécurisé, la publication d’articles par rubrique, la personnalisation éditoriale, le stockage d’images sur Cloudflare R2 et les notifications Resend. Le projet est déployé sur Railway.", stack: ["React", "Node.js", "MySQL", "Railway", "Cloudflare R2", "Resend"], bullets: ["Administration et publication d’articles", "Organisation du contenu par rubriques", "Stockage média Cloudflare R2", "Notifications transactionnelles via Resend"], site: "https://clairdroit-production.up.railway.app/", github: "https://github.com/YvanOssey/clairdroit", signature: "Le droit clair pour tous !", audiences: "Étudiants en droit, jeunes professionnels, entrepreneurs, salariés et lecteurs souhaitant mieux comprendre les règles qui encadrent leur vie personnelle ou professionnelle.", features: ["Navigation éditoriale par univers : actualité, vulgarisation, analyses et carrières", "Recherche d’articles et classement de chaque publication dans une seule rubrique", "Espace d’administration avec brouillons, publication, archivage et corbeille restaurable", "Personnalisation de l’identité éditoriale, des pages et des éléments de contact", "Formulaire de contact et newsletter avec notifications email"], architecture: [["Frontend", "React 19, TypeScript, Tailwind CSS 4"], ["Composants", "shadcn/ui, Radix UI, Lucide Icons"], ["Navigation & cache", "Wouter, TanStack React Query"], ["API & serveur", "tRPC 11, Node.js 18, Express"], ["Données", "Drizzle ORM et MySQL"], ["Build & tests", "Vite, esbuild, Vitest"]], security: "Authentification administrateur par sessions JWT, mots de passe hachés avec scrypt, validation serveur, liste d’emails autorisés, honeypot et confirmation renforcée avant suppression définitive.", role: "Conception de l’architecture, développement frontend et backend, modélisation MySQL, sécurisation de l’administration, intégration de R2 et Resend, tests, déploiement et accompagnement d’une utilisatrice non technique." },
};

export default function ProjectDetail() {
  const [, params] = useRoute("/projects/:slug");
  const [, navigate] = useLocation();
  const goBackToProjects = (event: MouseEvent<HTMLAnchorElement>) => { event.preventDefault(); navigate("/"); window.setTimeout(() => document.getElementById("projects")?.scrollIntoView({ behavior: "smooth", block: "start" }), 80); };
  const project = params ? details[params.slug] : undefined;
  if (!project) return <main className="detail-missing"><Link href="/">← Retour au portfolio</Link><h1>Projet introuvable.</h1></main>;

  return <div className="project-detail-page">
    <header className="detail-nav"><Link href="/" className="detail-brand">[YVAN.DEV]</Link><a href="/#projects" onClick={goBackToProjects} className="detail-back"><ArrowLeft size={15} /> Tous les projets</a></header>
    <main className="detail-main">
      <div className="detail-eyebrow"><span>PROJECT / {project.status.toUpperCase()}</span><span>2026</span></div>
      <div className="detail-heading"><div><p className="source-kicker">{project.type}</p><h1>{project.title}</h1><p className="detail-intro">{project.intro}</p></div><div className="detail-mark">{project.title.slice(0, 2).toUpperCase()}<span>↗</span></div></div>
      <div className="detail-layout"><article className="detail-copy"><p>{project.description}</p><h2>Ce que le projet met en place</h2><div className="detail-points">{project.bullets.map((bullet) => <div key={bullet}><CheckCircle2 size={16} /><span>{bullet}</span></div>)}</div></article><aside className="detail-aside"><span className="detail-aside-label">STACK TECHNIQUE</span><div className="detail-stack">{project.stack.map((item) => <span key={item}>{item}</span>)}</div>{(project.site || project.github) && <div className="detail-links">{project.site && <a href={project.site} target="_blank" rel="noreferrer">Voir le site <ArrowUpRight size={14} /></a>}{project.github && <a href={project.github} target="_blank" rel="noreferrer">Dépôt GitHub <Github size={14} /></a>}</div>}</aside></div>
      {project.features && <section className="detail-extra"><div className="detail-extra-heading"><span>01</span><h2>Produit &amp; expérience</h2></div><div className="detail-extra-grid"><div><span className="detail-aside-label">SIGNATURE ÉDITORIALE</span><blockquote>« {project.signature} »</blockquote></div><div><span className="detail-aside-label">PUBLICS CIBLÉS</span><p>{project.audiences}</p></div></div><div className="detail-feature-list">{project.features.map((feature, index) => <div key={feature}><span>0{index + 1}</span><p>{feature}</p></div>)}</div></section>}
      {project.architecture && <section className="detail-extra"><div className="detail-extra-heading"><span>02</span><h2>Architecture technique</h2></div><div className="detail-architecture">{project.architecture.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{project.security && <div className="detail-security"><ShieldCheck size={18} /><p><b>Sécurité &amp; fiabilité.</b> {project.security}</p></div>}</section>}
      {project.role && <section className="detail-extra detail-role"><div className="detail-extra-heading"><span>03</span><h2>Rôle réalisé</h2></div><p>{project.role}</p></section>}
      <a href="/#projects" onClick={goBackToProjects} className="detail-next"><ArrowLeft size={15} /> Revenir aux projets</a>
    </main>
  </div>;
}
